trigger: none

pool:
  name: LinuxPool

stages:
  - stage: buildStage
    jobs:
      - job: buildJobs
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker0395'
              repository: 'springboot'
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
          
